server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

---
spring:
  profiles: container
server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://cluster-discovery:8761/eureka/
  
