server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

---
spring:
  profiles: container
server:
  port: 8080

eureka:
  instance:
    hostname: inf-host
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://inf-host:8761/eureka/
