server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
alpha:
  description: World!! (Provided by the configuration server)

---
spring:
  profiles: container
server:
  port: 8080

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://inf-host:8761/eureka/
