server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

beta:
  description: from the Beta service.

---
spring:
  profiles: container

eureka:
  instance:
    hostname: ${DEPLOY_HOST:svc-host}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://inf-host:8761/eureka/
