server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
alpha:
  description: World!! (Provided by the configuration server)

---
spring:
  profiles: container

eureka:
  instance:
    hostname: ${DEPLOY_HOST:svc-host}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://inf-host:8761/eureka/
